import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { initializeDb } from "@fwens/server/schema";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MANAGED_BLOCK_START = "<!-- fwens:start -->";
const MANAGED_BLOCK_END = "<!-- fwens:end -->";

const AGENT_INSTRUCTION_FILENAMES = ["AGENTS.md", "CLAUDE.md", "GEMINI.md", "OPENCODE.md"] as const;

const INSTRUCTION_TEMPLATE_PATH = path.resolve(
  __dirname,
  "../../../../templates/fwens-instructions.md",
);

function buildManagedInstructionBlock(projectDir: string): string {
  const template = fs.readFileSync(INSTRUCTION_TEMPLATE_PATH, "utf-8").trimEnd();
  const dbPath = path.relative(projectDir, path.join(projectDir, ".fwens", "fwens.db"));
  const renderedTemplate = template.replaceAll("{{FWENS_DB_PATH}}", dbPath);

  return `${MANAGED_BLOCK_START}\n${renderedTemplate}\n${MANAGED_BLOCK_END}`;
}

function upsertManagedBlock(existing: string, managedBlock: string): string {
  const startIndex = existing.indexOf(MANAGED_BLOCK_START);
  const endIndex = existing.indexOf(MANAGED_BLOCK_END);

  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const before = existing.slice(0, startIndex).trimEnd();
    const after = existing.slice(endIndex + MANAGED_BLOCK_END.length).trimStart();
    return [before, managedBlock, after].filter(Boolean).join("\n\n") + "\n";
  }

  const trimmed = existing.trimEnd();
  return trimmed ? `${trimmed}\n\n${managedBlock}\n` : `${managedBlock}\n`;
}

function writeAgentInstructions(projectDir: string, fwensDir: string): void {
  const managedBlock = buildManagedInstructionBlock(projectDir);
  const instructionsDir = path.join(fwensDir, "agent-instructions");
  fs.mkdirSync(instructionsDir, { recursive: true });

  for (const filename of AGENT_INSTRUCTION_FILENAMES) {
    const projectInstructionPath = path.join(projectDir, filename);
    const existing = fs.existsSync(projectInstructionPath)
      ? fs.readFileSync(projectInstructionPath, "utf-8")
      : "";

    fs.writeFileSync(projectInstructionPath, upsertManagedBlock(existing, managedBlock));
    fs.writeFileSync(path.join(instructionsDir, filename), `${managedBlock}\n`);
  }
}

function writeMcpConfigs(mcpDir: string, projectDir: string): void {
  const serverPath = path.resolve(__dirname, "../../../server/dist/index.js");

  const machineNote =
    "NOTE: This file contains machine-specific absolute paths. It is generated by 'fwens init'.";

  const makeJsonConfig = (agentType: string) =>
    JSON.stringify(
      {
        _note: machineNote,
        mcpServers: {
          fwens: {
            command: "node",
            args: [serverPath],
            env: {
              FWENS_PROJECT: projectDir,
              FWENS_AGENT_TYPE: agentType,
            },
          },
        },
      },
      null,
      2,
    );

  fs.writeFileSync(path.join(mcpDir, "claude.json"), makeJsonConfig("claude") + "\n");
  fs.writeFileSync(path.join(mcpDir, "gemini.json"), makeJsonConfig("gemini") + "\n");
  // OpenCode uses a different JSON schema: "mcp" key, command as array, "environment" not "env"
  const opencodeConfig = JSON.stringify(
    {
      _note: machineNote,
      mcp: {
        fwens: {
          type: "local",
          command: ["node", serverPath],
          environment: {
            FWENS_PROJECT: projectDir,
            FWENS_AGENT_TYPE: "opencode",
          },
          enabled: true,
        },
      },
    },
    null,
    2,
  );
  fs.writeFileSync(path.join(mcpDir, "opencode.json"), opencodeConfig + "\n");
  // Codex CLI uses TOML format — escape values to prevent injection via special chars
  const escapeTomlString = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const codexToml = `# NOTE: This file contains machine-specific absolute paths. It is generated by 'fwens init'.
[mcp_servers.fwens]
command = "node"
args = ["${escapeTomlString(serverPath)}"]

[mcp_servers.fwens.env]
FWENS_PROJECT = "${escapeTomlString(projectDir)}"
FWENS_AGENT_TYPE = "codex"
`;
  fs.writeFileSync(path.join(mcpDir, "codex.toml"), codexToml);
}

export function runInit(projectDir: string): void {
  const fwensDir = path.join(projectDir, ".fwens");
  const mcpDir = path.join(fwensDir, "mcp-configs");

  // 1. Create directories
  fs.mkdirSync(fwensDir, { recursive: true });
  fs.mkdirSync(mcpDir, { recursive: true });

  // 2. Write config.json (skip if exists for idempotency)
  const configPath = path.join(fwensDir, "config.json");
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, JSON.stringify({ project_root: projectDir }, null, 2) + "\n");
  }

  // 3. Create and initialize SQLite database
  const dbPath = path.join(fwensDir, "fwens.db");
  const db = new Database(dbPath);
  initializeDb(db);
  db.close();

  // 4. Generate MCP config snippets
  writeMcpConfigs(mcpDir, projectDir);

  // 5. Install project instruction files so agents check fwens on startup
  writeAgentInstructions(projectDir, fwensDir);

  console.log(`Initialized fwens project at ${fwensDir}`);
}
